// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGXvKlQYb-90xo3SmdeUJE3wY7_A0mHog',
    appId: '1:97713718626:android:5140926cd2b6f4cb89d83b',
    messagingSenderId: '97713718626',
    projectId: 'medica-b77e1',
    storageBucket: 'medica-b77e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQUAcvufpZi_-_csJyK1FNkE0QxaVO4S4',
    appId: '1:97713718626:ios:db1deb38e75793c889d83b',
    messagingSenderId: '97713718626',
    projectId: 'medica-b77e1',
    storageBucket: 'medica-b77e1.appspot.com',
    iosBundleId: 'com.example.hospitalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQUAcvufpZi_-_csJyK1FNkE0QxaVO4S4',
    appId: '1:97713718626:ios:54de0263f174ac7a89d83b',
    messagingSenderId: '97713718626',
    projectId: 'medica-b77e1',
    storageBucket: 'medica-b77e1.appspot.com',
    iosBundleId: 'com.example.hospitalapp.RunnerTests',
  );
}
